project_id = "xuzhmzzvjufkjeypddlr"

[functions.save-mysql-config]
verify_jwt = false

[functions.verify-user-email]
verify_jwt = false

[functions.test-mysql-connection]
verify_jwt = false

[functions.import-wekan-board]
verify_jwt = false

[functions.generate-invite-token]
verify_jwt = false

[functions.redeem-invite-token]
verify_jwt = false
